### PR TITLE
Add support for building a snap via snapcraft

### PR DESCRIPTION
**Pull request by popey**
I created a snap package of hyperfine so it can be featured to the millions of Linux users installing apps from the [Snap Store](https://snapcraft.io/store). If you're willing to publish this under the hyperfine project name, you just need to [create an account](https://snapcraft.io/snaps) and then [register the hyperfine name](https://snapcraft.io/register-snap).

The snap file created by snapcraft can then be released in the Snap Store with snap push --release stable *.snap. You'll want to install snapcraft (brew install snapcraft, snap install snapcraft, or apt install snapcraft) and login (snapcraft login) first, though.

Once in the snap store, you’ll need to [request classic confinement](https://forum.snapcraft.io/t/process-for-reviewing-classic-confinement-snaps/1460) with a [forum post](https://forum.snapcraft.io/), because hyperfine will need to be unconfined (via classic confinement) so it has access to the entire filesystem.

You may also want to consider using [https://build.snapcraft.io/](https://build.snapcraft.io/) which is a free build service, that can create armhf, amd64, i386, arm64 and other builds of hyperfine, and push them to the store automatically.

Thanks for making hyperfine! :)

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you very much.

**Comment by sharkdp** [comment]
@popey I finally managed to get `snap` and `snapcraft` running on Arch Linux (it was a pain).

I also managed to build a snap for hyperfine successfully!

When I run `snapcraft push`, I get the following error (which is expected, I guess):

```
▶ snapcraft push --release stable *.snap
Pushing hyperfine_git_amd64.snap
After pushing, an attempt will be made to release to 'stable'
Preparing to push '/home/shark/Dropbox/Informatik/rust/hyperfine/hyperfine_git_amd64.snap' to the store.
Pushing hyperfine_git_amd64.snap [====================================================] 100%
Processing...|                                                                              
Will need manual review...
The Store automatic review failed.
A human will soon review your snap, but if you can't wait please write in the snapcraft forum asking for the manual review explicitly.
If you need to disable confinement, please consider using devmode, but note that devmode revision will only be allowed to be released in edge and beta channels.
Please check the errors and some hints below:
  - (NEEDS REVIEW) confinement 'classic' not allowed. If your snap needs classic confinement to function, please make a request for this snap to use classic by creating a new topic in the forum using the 'store' category and detail the technical reasons why classic is required.
```

I have two questions:
- Why do we actually need classic confinement for `hyperfine`?
- How do I manage to put a proper version on this snap? Do I need to `git checkout` a specific tag?

**Comment by popey** [comment]
Awesome! Yes, the response is expected. As 'classic' snaps are effectively unconfined, they need to go through a one-time human review (in public) on the snapcraft forum. That process is detailed at [this post](https://forum.snapcraft.io/t/process-for-reviewing-classic-confinement-snaps/1460). So everyone is aware that a developer is requesting that an unconfined application is going in the store and is able to provide input.

If you start a thread on the [snapcraft forum](https://snapcraft.io/) titled "Request for classic confinement: hyperfine", add a link to this PR & mention why it needs classic (it needs to be able to execute arbitrary binaries) it will be reviewed by someone on the security team.

**Comment by sharkdp** [comment]
@popey I did that (https://forum.snapcraft.io/t/request-for-classic-confinement-hyperfine/8985), thank you very much.

The generated snap file is currently called `hyperfine_git_amd64.snap` and the version is `0+git.b089eda`. Is that the way to go? I would have expected to have some way to specify the version (git tag).

**Comment by MatheusRV** [comment]
Friendly Ping

**Comment by sharkdp** [comment]
I've given up on snap. I invested several hours trying to build a simple package, but couldn't get it to work. If someone else wants to pick this up, I'm happy to transfer the registered package name.

**Pull request merged**
