### PR TITLE
Add Winget Releaser workflow

### LINKED ISSUE #307: WinGet-based installation
It would be really great to be able to install this on Windows through the [windows package manager, `winget`](https://docs.microsoft.com/en-us/windows/package-manager/winget/).

(Sorry, I know I've hit a few of your repos now. I'm just going through my heavily-used Rust tools and making issues like this on your repos because it would be awesome to install them through the native PM ❤️ . Forgive me the slight spam)

### PR DESCRIPTION
**Pull request by sitiom**
[This action](https://github.com/vedantmgoyal2009/winget-releaser) automatically generates manifests for Winget Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

**Before merging this:**
1. Add a **classic** PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN`.

example

2. Fork https://github.com/microsoft/winget-pkgs under @sharkdp. The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Install [Pull](https://github.com/apps/pull) on the winget-pkgs fork to ensure that it is constantly updated.

You can test out the action inputs in this [playground](https://bittu.eu.org/docs/wr-playground).

If you want to see an example of a PR created using this action, see [microsoft/winget-pkgs/pulls (Pull request has been created with WinGet Releaser)](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+sort%3Aupdated-desc+Pull+request+has+been+created+with+WinGet+Releaser).

- Resolves #307

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you. I would first like to understand if it's really necessary that I personally maintain this (I'd rather not, if possible). Couldn't that GA action run on a fork (of hyperfine, not winget - kept up to date by the pull action mentioned above) created by someone else?

**Comment by sitiom** [comment]
> I would first like to understand if it's really necessary that I personally maintain this

If you want the Winget package to be updated, that is. There isn't any built-in automation to Winget, unlike Scoop.

> Couldn't that GA action run on a fork (of hyperfine, not winget - kept up to date by the pull action mentioned above)

That's not how it works. The action submits a PR to https://github.com/microsoft/winget-pkgs via your winget-pkgs fork.

**Review by sharkdp — APPROVED** [review]

**Comment by sitiom** [comment]
@sharkdp Failed. The binaries weren't available in the releases: https://github.com/sharkdp/hyperfine/actions/runs/4424630811. Rerun them again once you have added them.

**Comment by sharkdp** [comment]
Well, the binaries are added by another GA pipeline. Maybe that pipeline can "wait" for the other one somehow? Or be delayed?

**Comment by sitiom** [comment]
I think I should've workflow should've been added inside https://github.com/sharkdp/hyperfine/blob/master/.github/workflows/CICD.yml instead.

**Comment by sharkdp** [comment]
It failed again

**Comment by sitiom** [comment]
image

It seems like you didn't add the `WINGET_TOKEN` secret in this repo.

**Comment by sharkdp** [comment]
> It seems like you didn't add the `WINGET_TOKEN` secret in this repo.

Oh, I missed that part in step 2. For future PRs, I would suggest to split that into two steps. Fixed now.

**Comment by sitiom** [comment]
> Oh, I missed that part in step 2

It's actually step 1 😅

> 1. Add a **classic** PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN`.

**Pull request merged**
