### PR TITLE
Switch to owo-colors.

### PR DESCRIPTION
**Pull request by inspier**
This pull request switches out the [colored](https://github.com/mackwic/colored) crate for [owo-colors](https://github.com/jam1garner/owo-colors).

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you for your contribution.

Why would we want to switch?

**Comment by inspier** [comment]
owo-colors has no dependencies and is no_std compatible, while the latter may not really be applicable to hyperfine it is perhaps still a win.

**Comment by sharkdp** [comment]
colored has served us well so far. Also, it's not like colored is not maintained anymore, right?

I don't really see a reason to switch to another dependency if there is no need. If the dependency tree is significantly smaller, that might be a reason to switch though.

**Comment by inspier** [comment]
`colored` has three dependencies atty, lazy_static, and winapi. While owo-colors has no dependencies and a near identical API for the most part. That said you make a fair point about not fixing something that isn't broken. So feel free to close this pull request or let me know if that is something I need to do.

**Comment by sharkdp** [comment]
> `colored` has three dependencies atty, lazy_static, and winapi

all of these are dependencies of `hyperfine` anyway.

> So feel free to close this pull request

I will close it for now, but we can come back to it if the situation changes. Thank you very much for your contribution.

**Comment by sharkdp** [comment]
Maybe the main reason not to introduce new dependencies is that package maintainers often have a hard time to package the new dependencies.

**Pull request closed without merging**
