### PR TITLE
correctly estimate full execution time

### LINKED ISSUE #27: Correctly estimate full execution time if --prepare is used
The estimated execution time should include the time to run the preparation command, e.g:
```
hyperfine --prepare 'sleep 10' 'sleep 0.1'
```

### PR DESCRIPTION
**Pull request by rleungx**
Resolves #27.

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you for working on this.

Probably I didn't explain it carefully in the attached ticket, but we definitely don't want to add the execution time of the preparation-command to the actual timing results (`times_real`, etc). The preparation command can be used to do some clean-up work and we don't want that to be included in the time measurement.

We do, however, want to measure the execution time of the preparation command once (like you did) and use it to correctly estimate `runs_in_min_time`. Otherwise, a long-running preparation command would lead to unusually long benchmark times (see the example in the attached ticket).

**Comment by rleungx** [comment]
Thanks for your explaination! I misunderstood the purpose of this issue.

**Comment by rleungx** [comment]
@sharkdp Please correct me if I'm still wrong.

**Comment by sharkdp** [comment]
Looks great, thank you very much

**Pull request merged**
