### PR TITLE
Nicer whiskers plot

### PR DESCRIPTION
**Pull request by serpent7776**
- add missing encoding when opening input file
- add labels to x ticks, rotated by 45 deg
- sort data by median, ascending

I like this layout much more, but if needed I can hide new functionality behind command line flags.

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you!

Can you provide a before-and-after screenshot?

> sort data by median, ascending

This would be nice to have as an option, but I prefer benchmarks to be ordered by input ordering — by default.

**Comment by serpent7776** [comment]
Sure, here's the old version:

plot_old

This is the new version (one issue is that longer labels are cut off):

plot_new

I can fix the issue by applying `plt.figure(figsize=(10, 6), constrained_layout=True)`, but I don't know why this works:

plot_sized

**Comment by sharkdp** [comment]
Cool — looks great! If we can hide the sorting feature behind a command line option (maybe `--sort-by=…`), I'm happy to merge this.

**Comment by serpent7776** [comment]
Updated the code.

**Review by sharkdp — APPROVED** [review]

**Comment by sharkdp** [comment]
Thank you

**Pull request merged**
