### PR TITLE
Windows compatibility (WIP)

### PR DESCRIPTION
**Pull request by sharkdp**
Follow up for #30.

/CC @stevepentland

### CODE REVIEW

**Comment by stevepentland** [comment]
I like these changes, I hadn't thought to hide the entire use inside of a function like that.

**Comment by sharkdp** [comment]
Thank you for the review.

For now, this will show 0.0 as user/system time on Windows.

Maybe there is a way to measure CPU times of the child processes via [`GetProcessTimes`](https://docs.rs/winapi/*/x86_64-pc-windows-msvc/winapi/um/processthreadsapi/fn.GetProcessTimes.html) on Windows.

**Comment by sharkdp** [comment]
I'm actually going to merge this, as it fixes #28. I'll open a new ticket for proper support on Windows.

**Comment by stevepentland** [comment]
I’ll look into the windows performance API for a bit and see if we can fill the gap

**Pull request merged**
